### ISSUE TITLE
Introduce IMPULSE_LINK

### ISSUE THREAD

**Issue by Yidnekachew** [singnet/asmoses#82]
Impulse is a unary function defined as 

```
I(x) = { 1, if x = True
       { 0, otherwise

where x is boolean.
````
We'll be defining an IMPULSE_LINK  in `<ASMOSES_ROOT>/opencog/atomese/atom_types` directory.

It can be declared as 

`IMPULSE_LINK <- FUNCTION_LINK,NUMERIC_OUTPUT_LINK,BOOLEAN_LINK`

**Comment by behailu04** [comment]
@Yidnekachew maybe it's good to look into how **CondLink** is implemented since the implementation is a little bit similar.

**Comment by Yidnekachew** [comment]
@behailu04 Thanks!

@ngeiswei The Atomese equivalent of `impulse` in combo will consider only evaluateable links. 

Can we generalize it to have a look at the truth values of both evaluatable and executable links?

If so, `ImpulseLink` would just be a special type of `CondLink` with its outputs being `Number(0)` and `Number(1)`

**Comment by ngeiswei** [comment]
> @ngeiswei The Atomese equivalent of impulse in combo will consider only evaluateable links.

@Yidnekachew , don't worry too much about the atom type hierarchy for now, since it remains on the asmoses repo for now.

Youare right that `ImpulseLink` is a specialized `CondLink`, I suppose it still needs its own syntax and interpreter though, as you probably agree.
